# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13db392487f9ee94e829f908611bf2b758a83899c3e966ff8e9fb88bb295399211af49fcef1b89069981269eaa29bf9df8bb1c83c402e34ee7f95be5dd34b05b

test:
  secret_key_base: d239328b6014bcf7acf0c4bf78b86a2867b09cc5b22cef39cc9b3f98b5a938f0ace0de45f649b746aa1105e1ed85d53de2a0aceb58f84d544a5b779a1efafdfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
